default_velocity_scaling_factor: 0.3
default_acceleration_scaling_factor: 0.3
joint_limits:
  shoulder_pan:  {has_velocity_limits: true, max_velocity: 3.0, has_acceleration_limits: true, max_acceleration: 3.0}
  shoulder_lift: {has_velocity_limits: true, max_velocity: 3.0, has_acceleration_limits: true, max_acceleration: 3.0}
  elbow_flex:    {has_velocity_limits: true, max_velocity: 3.0, has_acceleration_limits: true, max_acceleration: 3.0}
  wrist_flex:    {has_velocity_limits: true, max_velocity: 3.0, has_acceleration_limits: true, max_acceleration: 3.0}
  wrist_roll:    {has_velocity_limits: true, max_velocity: 3.0, has_acceleration_limits: true, max_acceleration: 3.0}
  gripper:       {has_velocity_limits: true, max_velocity: 3.0, has_acceleration_limits: true, max_acceleration: 3.0}
